export const regular = {
  name: /^[\u4e00-\u9fa5]{0,8}$/,
  mobile: /^1[3-9]\d{9}$/,
  email: /^([\w-_]+(?:\.[\w-_]+)*)@((?:[a-z0-9]+(?:-[a-zA-Z0-9]+)*)+\.[a-z]{2,6})$/i,
  password1: /^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,16}$/, // 6-16位数字和字母组成
  password: /^[0-9a-zA-Z]{6,20}$/, // app密码正则（6-20位）
  graphCode: /^\d{4}$/,
  codeTx: /^[A-Za-z0-9]{4}$/, // 4位字母数字或组合
  scode: /^\d{6}$/,
};
export const errorMsg = {
  MOBILE_NULL: '请输入手机号码',
  MOBILE_INVALID: '请输入正确的手机号码',
  PASSWORD_NULL: '请输入密码',
  PASSWORD_INVALID: '请输入6-20位字母、数字或组合的密码',
  PASSWORD_LENGTH: '密码长度应为6-20位',
  GRAPHCODE_NULL: '请输入图形验证码',
  GRAPHCODE_INVALID: '请输入正确的图形验证码',
  SMSCAPTCHA_NOT: '请先获取短信验证码',
  SMSCAPTCHA_NULL: '请输入短信验证码',
  SMSCAPTCHA_INVALID: '请输入正确的短信验证码',
  SMSCAPTCHA_SUCCESS: '验证码发送成功',
  AGREEMENT_NULL: '请勾选注册协议',

  PASSWORD_NEW_NULL: '请填写新密码',
  PASSWORD_AGAIN_NULL: '请填写密码确认',
  PASSWORD_AGAIN_INVALID: '两次输入的密码不一致',
  REPASSWORD_NULL: '请填写密码确认',
  REPASSWORD_INVALID: '两次输入的密码不一致',
  MOBILE_USED: '手机号码已被使用',
  CAPTCHA_TUXINGYZM: '请输入正确的图形验证码',
  MOBILE_CAPTCHA_NULL: '请填写手机短信验证码',
  MOBILE_CAPTCHA_INVALID: '验证码无效或已过期，请尝试重新发送',
  MOBILE_CAPTCHA_EXPIRED: '验证码过期，请尝试重新发送',
  AGREEMENT_NULL: '注册需先同意服务条款',
  CAPTCHA_NULL: '请填写验证码',
  CAPTCHA_INVALID: '请输入正确的验证码',
  LOGINNAME_EXISTS: '用户名已存在',
  LOGINNAME_STRICT: '2至15位中英文字符、数字或下划线',
  LOGINNAME_NULL: '请填写用户名',
  LOGINNAME_INVALID: '2至15位中英文字符、数字或下划线',
  LOGINNAME_SIZE: '2至15位中英文字符、数字或下划线',
  LOGINNAME_NOT_MOBILE: '用户名不能是手机号（注册后可以用手机号登录）',
  LOGINNAME_NOT_EMAIL: '用户名不能是邮箱',
  NAME_NULL: '请输入您的姓名',
  NAME_INVALID: '姓名错误，最多8位中文汉字',
  EMAIL_NULL: '请填写电子邮箱',
  EMAIL_INVALID: '请输入正确的邮箱',
  IDNUMBER_INVALID: '请正确填写 18 位身份证号码',
  LOGIN_INVALID: '手机号或密码错误',
  INVALID_CAPTCHA: '验证码错误',
  LOGINNAME_NOT_MATCH: '手机号码与登录名不匹配',
  INVITATION_INVALID: 'H码无效',
  INVITATION_NULL: 'H码为空',
  PAYMENT_ACCOUNT_CREATE_ERROR: '国政通实名认证校验未通过',
  IDNUMBER_NULL: '身份证号不能为空'
};
